namespace: "ji_podhead"
name: "host_prototypes"
description:  "a little collection that creates hosts from prototypes. it also creates private,public keys, random mac and random pass"
version: "0.0.4"
readme: "README.md"
authors:
    - "ji-podhead (https://https://www.github.com/ji-podhead)"
dependencies:
    community.general: ">=0.0.0"
license:
    - "MIT"
tags:
    - host_prototypes
    - random_mac_and_random_pass
    - random_ssh_keys
    - dynamic_host_createn

repository: "https://www.github.com/the-pod-shop/host_prototypes"



